#! /bin/sh

# dclip || Delta 26dic08

file=$HOME/.dclip_cache
size=10

if [ "$1" == "copy" ]; then
    sel_clip=$(xclip -o)
    sel_file=$(echo -n "$sel_clip"|tr '\n' '¶')
fi
if [ "$1" == "paste" ]; then 
    shift 
    touch $file 
    sel_file=$(cat $file | dmenu ${1+"$@"}) 
    sel_clip=$(echo -n "$sel_file"|tr '¶' '\n')
fi
[ "$sel_clip" == "" ] && exit 1

sed "/^$sel_file$/d" -i $file
cut=$(head -n $(($size-1)) $file)
echo "$sel_file" > $file
echo -n "$cut" >> $file

echo -n "$sel_clip" | xclip -selection primary -i
echo -n "$sel_clip" | xclip -selection clipboard -i
 
exit 0
